/********************************************************************
* NMMEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NMMEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNMMEventDict();
extern void G__cpp_setup_inheritanceNMMEventDict();
extern void G__cpp_setup_typetableNMMEventDict();
extern void G__cpp_setup_memvarNMMEventDict();
extern void G__cpp_setup_globalNMMEventDict();
extern void G__cpp_setup_memfuncNMMEventDict();
extern void G__cpp_setup_funcNMMEventDict();
extern void G__set_cpp_environmentNMMEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NMMEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NMMEventDictLN_TClass;
extern G__linked_taginfo G__NMMEventDictLN_TBuffer;
extern G__linked_taginfo G__NMMEventDictLN_TMemberInspector;
extern G__linked_taginfo G__NMMEventDictLN_TObject;
extern G__linked_taginfo G__NMMEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__NMMEventDictLN_string;
extern G__linked_taginfo G__NMMEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NMMEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NMMEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NMMEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NMMEventDictLN_NMMEvent;
extern G__linked_taginfo G__NMMEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__NMMEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
